# Generated by Django 5.0.1 on 2024-03-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card/image/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/videos')),
                ('title', models.CharField(max_length=150)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.card')),
            ],
        ),
    ]
