# Generated by Django 5.0.1 on 2024-03-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.theme'),
        ),
    ]
