# Generated by Django 5.0.1 on 2024-03-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='course_app.card'),
        ),
    ]
