# Generated by Django 5.0.1 on 2024-03-12 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_theme_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='course_app.theme'),
        ),
    ]
